# Generated by Django 4.2.7 on 2023-11-02 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publish",
            old_name="decsciption",
            new_name="description",
        ),
    ]
