# Generated by Django 4.2.7 on 2023-11-03 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_publish_useri"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publish",
            name="useri",
        ),
    ]
