# Generated by Django 4.2.7 on 2023-11-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_publish_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="publish",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
