# Generated by Django 4.2.5 on 2023-11-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publish",
            name="image",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
